name: laptopHarbor
description: A new Flutter project for LaptopHarbor
publish_to: 'none' # Remove this line if you plan to publish
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
